services:
    frontend:
      build:
        context: ./frontend
        dockerfile: ../frontend/Dockerfile
      volumes:
        - ./frontend:/workspace/app
      healthcheck:
        test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:5173/"]
        interval: 1s
        timeout: 3s
        retries: 10
        start_period: 10s

    backend:
      build:
        context: ./backend
        dockerfile: ../backend/Dockerfile
      volumes:
        - ./backend:/workspace/app
      environment:
        HOSTNAME: ${HOSTNAME:?HOSTNAME is not set}
      healthcheck:
        test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:3000/api/ping"]
        interval: 1s
        timeout: 3s
        retries: 10
        start_period: 10s
      secrets:
       - backend_vault_token

    nginx_dev:
      build: 
        dockerfile: ./nginx/dev.Dockerfile
        context: .
      depends_on:
        frontend:
          condition: service_healthy
        backend:
          condition: service_healthy
        grafana:
          condition: service_healthy
      ports:
        - "8443:443"

    postgres:
      image: postgres:18.4
      volumes:
        - postgres_data:/var/lib/postgresql
        - ./postgres/init:/docker-entrypoint-initdb.d:ro
      environment:
        POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
        POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not set}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
        interval: 5s
        timeout: 3s
        retries: 10

    postgresexporter:
      build: ./postgres/exporter
      secrets:
        - exporter_vault_token

    nginx_exporter:
      image: nginx/nginx-prometheus-exporter:1.5.1
      command: ["--nginx.scrape-uri", "http://nginx_dev:3001/stub_status"]
 
    prometheus:
      image: prom/prometheus:v3.13.1
      volumes:
        - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - prometheus:/prometheus
      healthcheck:
        test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/ready"]
        interval: 5s
        timeout: 3s
        retries: 10
      command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-admin-api


    grafana:
      image: grafana/grafana:13.0-slim
      environment:
        GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana_admin_user
        GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
        GF_LOG_LEVEL: warn
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"
        GF_SERVER_ROOT_URL: "https://monitoring.localhost:8443/"
      volumes:
        - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
        - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
        - grafana:/var/lib/grafana
      secrets:
        - grafana_admin_user
        - grafana_admin_password
      healthcheck:
        test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:3000/api/health"]
        interval: 1s
        timeout: 3s
        retries: 10
        start_period: 10s

    backups:
      build: ./backups
      volumes:
        - prometheus:/app/prometheus
        - grafana:/app/grafana
        - postgres_data:/app/postgress
        - ./backups/backups:/app/backups
      depends_on:
        prometheus:
          condition: service_healthy
        postgres:
          condition: service_healthy

    vault-init:
      image: hashicorp/vault:1.20.4
      user: "0:0"
      volumes:
        - vault_data:/vault/data
      command:
        - sh
        - -c
        - |
          chown -R 100:1000 /vault/data

    vault:
      image: hashicorp/vault:1.20.4
      container_name: vault
      restart: unless-stopped
      depends_on:
        vault-init:
          condition: service_completed_successfully
      cap_add:
        - IPC_LOCK
      ports:
        - "127.0.0.1:8200:8200"
      environment:
        VAULT_ADDR: http://127.0.0.1:8200
      volumes:
        - vault_data:/vault/data
        - ./vault/config/vault.hcl:/vault/config/vault.hcl:ro
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "wget -q -O /dev/null 'http://127.0.0.1:8200/v1/sys/health?sealedcode=200&uninitcode=200'"
          ]
        interval: 5s
        timeout: 3s
        retries: 10
      command: vault server -config=/vault/config/vault.hcl

volumes:
  prometheus:
  grafana:
  postgres_data:
    name: ${POSTGRES_VOLUME_NAME:-ft_transcendence_postgres_data}
  vault_data:

secrets:
  backend_vault_token:
    file: ./tokens/.backend_vault_token
  exporter_vault_token:
    file: ./tokens/.postgres_exporter_token
  grafana_admin_user:
    file: ./tokens/grafana/admin_user
  grafana_admin_password:
    file: ./tokens/grafana/admin_password