error_log /dev/stderr warn;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_certificate /etc/nginx/ssl/nginx.crt;
ssl_certificate_key /etc/nginx/ssl/nginx.key;

error_page 497 =301 https://$host:8443$request_uri;

proxy_http_version 1.1;

proxy_set_header Host $host;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";


server {
	listen 443 ssl;
	server_name localhost;

	# API
	location /api/ {
		proxy_pass http://backend:3000;
	}

	# Socket.IO
	location /socket.io/ {
		proxy_pass http://backend:3000;

		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}

	# Backend HTML pages
	location = /setup-2fa {
		proxy_pass http://backend:3000;
	}

	location = /verify-2fa {
		proxy_pass http://backend:3000;
	}

	location = /verify-email {
		proxy_pass http://backend:3000;
	}

	# Frontend
	location / {
		proxy_pass http://frontend:3000;
	}

	# Static pages
	location = /privacy {
		alias /var/www/pages/privacy.html;
		default_type text/html;
	}

	location = /terms {
		alias /var/www/pages/terms.html;
		default_type text/html;
	}

	location = /legal.css {
		alias /var/www/pages/legal.css;
		default_type text/css;
	}
}


server {
	listen 3001;
	server_name localhost;

	stub_status;
	access_log off;
}


server {
	listen 443 ssl;
	server_name monitoring.localhost;

	location / {
		proxy_pass http://grafana:3000;
	}
}
