name: CI

on:
  pull_request:
    branches: [main]

jobs:
  App:
    runs-on: ubuntu-latest
    needs: [frontend-build, backend-build, codestyle]
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Create .env file
        run: mv .env.example .env

      - name: Build, start, and wait for containers
        run: docker compose up --build --detach --wait --wait-timeout 60

      - uses: actions/setup-python@v6

      - name: Install Chromium
        run: |
          mkdir -p /tmp/chrome
          cd /tmp/chrome
          npm init -y
          npm install playwright
          npx playwright install --with-deps chromium
          cd ../

      - name: Create account
        run: python script/signup.py

  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run typecheck

      - name: Try to compile frontend
        run: npm run build

  backend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run typecheck

  codestyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, backend]

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint
